# Summary

This document (hereafter refered to as "the replication study") provides a technical description of the process we are following to reproduce and replicate the work titled "A forest loss report card for the world’s protected areas" published in *Nature Ecology & Evolution* by Wolf, Levi, Ripple, Zárrate-Charry and Betts [-@wolf2021, hereafter referred to as "the original study"]. Before starting any analysis, we specified the objectives of this exercises and the different steps we intend to follow in @sec-preanalysis_plan. Our intents to create a computing environment able to run the original study's code is presented in @sec-computing_setup. The code published alongside the original study automatically fetches a subset of the data required by the statistical computation, but some sources links need to be updated. @sec-data_preparation describes these updates and how to obtain the data that is missing when using only the published code. @sec-reproducion_asis describes the subsequent steps followed to execute the code, including the first coding errors that we found. The code for the matching algorithm fails to run, we are not able to debug it and the corresponding author of the original study is not available to debug it. We therefore decided to re-implement the data analysis process described in the original study but in a way that could be more straightforward, less error-prone and reproducible. We describe these intents in @sec-reimplement. We describe some issues we identified in the analysis process of the original study in @sec-observations.